#!/bin/sh

function get_title() {
cat << "EOF"
     A+-----------+     +---B----+  __C_________D_     E____                   G____ H___    _______ R
      A\_____     /    /   B    /   \ C          D\   E/    \    b  R+ b       G/    \H   \   \     / R
       A\___     /    /   B    /    /  C  _____ D  \  E\____/ F___________     G\____/H    \   |   | R
        A\_     /____/   B    /    /   C /     \D   \ E______F/           \    G___H|G____H   \  |   |  I__________ R
         A/             B     \___/   C /      D|   |E|     F/    _____    \  G|_      /H\   \ |   | I/          \ R
        A/     ____     /B\          C |______D/   / E/    F/    /     \____\ G /     /H| \   \|   |I/   .---+    | R
       A/     /   /    /B  \_____   C  ___D_______/ E/    F/    /             G/     / H|  \   |   I|   /    |    | R
      A/     /   /    /B        /  C /   D\    \   E/    /F\    \       _____G/     /  H|   \  |   I|   \____/    | R
     A+-----+   /    /B \______/  C /     D\    \_E/    /  F\    \_____/    G/     /   H|    \     I|             | R
              A+---+B/           C /       D\     \E   /_   F\             G/     /_   H|     \    |I\_____      / R
        I_____      B\___________C_\       D/______\E __/    F\___________G/_______/H___|     /____|I     /     / R
        I\    \                                                                                  /     / R
         I\    `--------------------------------------------------------------------------------/     / R
          I\_________________________________________________________________________________________/ R
EOF
}

blue="2;110;170;251m"
red="2;235;110;103m"
green="2;149;238;143m"
yellow="2;248;196;86m"
purple="2;216;134;243m"
black="2;0;0;0m"

get_title \
  | sed -r "s/b/`printf "\e[38;$blue"`/g" \
  | sed -r "s/A/`printf "\e[38;$red"`/g" \
  | sed -r "s/B/`printf "\e[38;$green"`/g" \
  | sed -r "s/C/`printf "\e[38;$yellow"`/g" \
  | sed -r "s/D/`printf "\e[38;$blue"`/g" \
  | sed -r "s/E/`printf "\e[38;$purple"`/g" \
  | sed -r "s/F/`printf "\e[38;$blue"`/g" \
  | sed -r "s/G/`printf "\e[38;$yellow"`/g" \
  | sed -r "s/H/`printf "\e[38;$green"`/g" \
  | sed -r "s/I/`printf "\e[38;$red"`/g" \
  | sed -r "s/R/`printf "\e[0m"`/g"

if [ "$#" -gt 0 ] && [ $1 -ne 0 ]; then
  echo ""
  printf "\e[48;$blue\e[38;$black   User   \e[0m `whoami`\n"
  printf "\e[48;$red\e[38;$black   Host   \e[0m `uname -n`\n"

  DISK_SIZE_TOTAL=$(df -kh . | tail -n1 | awk '{print $2}')
  DISK_SIZE_USED=$(df -kh . | tail -n1 | awk '{print $3}')
  DISK_PERCENT_USED=$(df -kh . | tail -n1 | awk '{print $5}')
  printf "\e[48;$green\e[38;$black   Disk   \e[0m $DISK_SIZE_USED/$DISK_SIZE_TOTAL ($DISK_PERCENT_USED%)\n"

  printf "\e[48;$yellow\e[38;$black  Kernel  \e[0m `uname -sr`\n"
  printf "\e[48;$purple\e[38;$black Packages \e[0m `pacman -Qq | wc -l`\n"
  printf "\e[48;$green\e[38;$black  Uptime  \e[0m`uptime`\n"
fi
