#!/bin/sh

function npm_ginstall() {
  if command -v npm &> /dev/null; then
    sudo npm i -g $1
  else
    echo "npm not found!"
    read -p "Install NPM? (y/N/q: quit) " $confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      sudo pacman -S --needed nodejs npm
      npm_ginstall $1
    elif [ "$confirm" = "q" ] || [ "$confirm" = "Q" ]; then
      exit 0
    fi
  fi
}

# lua_ls
if ! command -v lua-language-server &> /dev/null; then
  echo "installing lua_ls..."
  sudo pacman -S lua-language-server
fi

# rust_analyzer
if ! command -v rust-analyzer &> /dev/null; then
  echo "installing rust_analyzer..."
  curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer
  chmod +x ~/.local/bin/rust-analyzer
fi

# tsserver
if ! command -v tsserver &> /dev/null; then
  echo "installing tsserver..."
  npm_ginstall tsserver
fi

# cssls, html, jsonls
if ! command -v vscode-css-language-server &> /dev/null; then
  echo "installing vscode-langservers-extracted..."
  npm_ginstall vscode-langservers-extracted
fi

# emmet-ls
if ! command -v emmet-ls &> /dev/null; then
  echo "installing emmet-ls..."
  npm-ginstall emmet-ls
fi

# intelephense
if ! command -v intelephense &> /dev/null; then
  echo "installing intelephense..."
  npm_ginstall intelephense
fi

# ccls
if ! command -v ccls &> /dev/null; then
  echo "installing ccls..."
  sudo pacman -S --needed ccls
fi

# taplo
if ! command -v taplo &> /dev/null; then
  echo "installing taplo..."
  sudo pacman -S --needed taplo-cli
fi

# gopls
if ! command -v gopls &> /dev/null; then
  echo "installing gopls..."
  if command -v go &> /dev/null; then
    go install golang.org/x/tools/gopls@latest
  else
    sudo pacman -S gopls
  fi
fi
