#!/bin/sh

sudo pacman -S --needed hyprland fish rofi-wayland waybar swaync alacritty swaybg neovim tmux fzf exa trash-cli brightnessctl jq

if ! command -v taplo &> /dev/null; then
  if ! command -v cargo &> /dev/null; then
    cargo install taplo-cli
  else
    echo "Cargo Not Installed"
    read -p "Install cargo? (y/N/q: quit) " $confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      curl https://sh.rustup.rs -sSf | sh
      cargo install taplo-cli
    elif [ "$confirm" = "q" ] || [ "$confirm" = "Q" ]; then
      exit 0
    fi
  fi
fi

if ! [ -d "$HOME/.config" ]; then
  mkdir "$HOME/.config"
fi

for config in .config/*; do
  copy=1
  if [ -e "$HOME/$config" ]; then
    echo "$config exists in $HOME/$config backup to $HOME/$config.$USER"
    echo "y: Create Backup, (n or other): Dont Copy This Config, q: Quit Installation, r: Remove Existing Config"
    read -p "Create Backup For $config? (y/q/r/N) " confirm
    if [ "$confirm" = 'y' ] || [ "$confirm" = 'Y' ]; then
      mv "$HOME/$config" "$HOME/$config.$USER"
    elif [ "$confirm" = 'q' ] || [ "$confirm" = 'Q' ]; then
      exit 0
    elif [ "$confirm" = 'r' ] || [ "$confirm" = 'R' ]; then
      rm -fr "$HOME/$config"
    else
      copy=0
    fi
  fi
  if [ $copy -eq 1 ]; then
    cp -r "$config" "$HOME/$config"
  fi
done

if ! [  -d "$HOME/.fonts" ]; then
  mkdir "$HOME/.fonts"
fi
cp -r .fonts/* "$HOME/.fonts"

if ! [  -d "$HOME/.icons" ]; then
  mkdir "$HOME/.icons"
fi
cp -r .icons/* "$HOME/.icons"

if ! [  -d "$HOME/.themes" ]; then
  mkdir "$HOME/.themes"
fi
cp -r .themes/* "$HOME/.themes"
