shell = "fish"
live_config_reload = true

[window]
padding = { x = 0, y = 0 }
opacity = 0.8
blur = true

[font]
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
size = 8.5

[mouse]
hide_when_typing = true

[colors.primary]
background = '0x1e2127'
foreground = '0xabb2bf'
dim_foreground = '0x9a9a9a'
bright_foreground = '0xe6efff'

[colors.normal]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta ='0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'

[colors.bright]
black = '0x5c6370'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0xe6efff'

[colors.dim]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'
